(() => {
  const STYLE_ID = "nicheforge-scout-style", BAR_ID = "nicheforge-scout-bar";
  let timer, lastKeyword = "", lastUrlsKey = "";
  function organicLinks() { const seen = new Set(), rows = []; for (const a of document.querySelectorAll("a")) { const h3 = a.querySelector("h3"); if (!h3 || !a.href) continue; try { const url = new URL(a.href); if (!["http:", "https:"].includes(url.protocol) || seen.has(url.href)) continue; seen.add(url.href); rows.push({a, url: url.href}); } catch {} } return rows.slice(0, 10); }
  function style() { if (document.getElementById(STYLE_ID)) return; const el = document.createElement("style"); el.id = STYLE_ID; el.textContent = `#${BAR_ID}{position:relative;z-index:1000;display:flex;gap:8px;align-items:center;padding:7px 14px;background:#15171c;color:#bfc5d2;font:600 12px Arial;border-bottom:1px solid #343944;box-shadow:0 2px 8px #0002}#${BAR_ID} .ns-brand{font-size:16px;font-weight:900;color:#fff;letter-spacing:-1px;margin-right:4px}#${BAR_ID} .ns-item{padding:4px 8px;border:1px solid #343944;border-radius:7px;white-space:nowrap}#${BAR_ID} .ns-status{color:#9aa3b2;font-weight:500}.ns-trend-bars{display:inline-flex;align-items:end;gap:2px;height:15px;margin-left:5px;vertical-align:middle}.ns-trend-bars i{display:block;width:3px;min-height:2px;border-radius:2px 2px 0 0;background:#7890d8}.nicheforge-scout-dr{display:inline-block;margin:2px 0 0 4px;padding:2px 5px;border-radius:4px;background:#e9f8ed;color:#14833b;font:700 11px Arial;vertical-align:middle}.nicheforge-scout-dr.ns-missing{color:#78848e;background:#f1f3f5}`; document.documentElement.appendChild(el); }
  function insertBar() { style(); if (document.getElementById(BAR_ID)) return; const bar = document.createElement("div"); bar.id = BAR_ID; bar.innerHTML = `<span class="ns-brand">NS</span><span class="ns-item">VOL <b id="ns-vol">—</b></span><span class="ns-item">AVG CPC <b id="ns-cpc">—</b></span><span class="ns-item">COMP <b id="ns-comp">—</b></span><span class="ns-item">TREND <b id="ns-trend">—</b></span><span class="ns-status" id="ns-status">NicheForge Scout</span>`; const anchor = document.querySelector("#searchform") || document.querySelector("form[role=search]"); (anchor?.parentElement || document.body).prepend(bar); }
  function set(id, value) { const el = document.getElementById(id); if (el) el.textContent = value == null ? "—" : String(value); }
  function renderMetrics(result) { const item = result?.results?.[0]; if (!item) { set("ns-status", result?.error || "Google Ads data unavailable"); return; } set("ns-vol", item.avg_monthly_searches?.toLocaleString?.() ?? item.avg_monthly_searches); const cpc = item.usd_cpc != null ? `$${Number(item.usd_cpc).toFixed(2)}` : (item.cpc != null ? `${item.provider_currency_code || "provider currency"} ${Number(item.cpc).toFixed(2)}` : "—"); set("ns-cpc", cpc); const index = item.competition_index ?? null; const level = index == null ? (item.competition == null ? "—" : String(item.competition)) : (index <= 33 ? "LOW" : index <= 66 ? "MEDIUM" : "HIGH"); set("ns-comp", index == null ? level : `${level} ${index}`); const history = Array.isArray(item.monthly_history) ? item.monthly_history : []; const values = history.map(x => Number(x.searches || 0)), max = Math.max(...values, 1); const trend = document.getElementById("ns-trend"); if (trend) trend.innerHTML = history.length ? `<span class="ns-trend-bars" title="12-month Google Ads search history">${history.map(x => `<i style="height:${Math.max(2, Math.round(Number(x.searches || 0) / max * 15))}px" title="${x.year}-${String(x.month).padStart(2, "0")}: ${Number(x.searches || 0).toLocaleString()}"></i>`).join("")}</span>` : "—"; set("ns-status", `Google Ads · ${item.mapping_status || "MAPPED"} · ${result.target_country || "WORLD"}`); }
  function detectCountry() { const gl = (new URLSearchParams(location.search).get("gl") || "").trim().toUpperCase(); return /^[A-Z]{2}$/.test(gl) ? gl : "WORLD"; }
  function renderDr(rows, byUrl) { for (const row of rows) { if (row.a.parentElement?.querySelector(".nicheforge-scout-dr")) continue; const data = byUrl?.[row.url], badge = document.createElement("span"); badge.className = "nicheforge-scout-dr" + (data?.dr == null ? " ns-missing" : ""); badge.textContent = data?.dr == null ? "DR —" : `DR ${data.dr}`; const host = row.a.parentElement; if (host?.parentElement) host.parentElement.insertBefore(badge, host); else if (host) host.insertBefore(badge, row.a); } }
  function refresh() { insertBar(); const keyword = new URLSearchParams(location.search).get("q") || "", rows = organicLinks(), urlsKey = rows.map(x => x.url).join("|"); if (keyword && keyword !== lastKeyword) { lastKeyword = keyword; chrome.runtime.sendMessage({type: "NS_RESEARCH_KEYWORD", keyword, countryCode: detectCountry()}, response => { if (response?.ok) renderMetrics(response.data); else set("ns-status", response?.error || "Google Ads unavailable"); }); } if (rows.length && urlsKey !== lastUrlsKey) { lastUrlsKey = urlsKey; chrome.runtime.sendMessage({type: "NS_LOOKUP_DR", urls: rows.map(x => x.url)}, response => { if (response?.ok) renderDr(rows, response.data?.by_url || {}); }); } }
  refresh(); new MutationObserver(() => { clearTimeout(timer); timer = setTimeout(refresh, 500); }).observe(document.documentElement, {subtree: true, childList: true});
})();
