const DEFAULT_API = "http://localhost:8000/api/v1";
async function settings() { return new Promise(resolve => chrome.storage.local.get({apiBase: DEFAULT_API, accessToken: ""}, resolve)); }
async function api(path, init = {}) { const s = await settings(); const headers = {"Content-Type": "application/json", ...(init.headers || {})}; if (s.accessToken) headers.Authorization = `Bearer ${s.accessToken}`; const response = await fetch(`${String(s.apiBase).replace(/\/$/, "")}${path}`, {...init, headers}); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.detail || `API request failed (${response.status})`); return data; }
chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
  if (message?.type === "NS_RESEARCH_KEYWORD") { api("/keyword-metrics/research", {method: "POST", body: JSON.stringify({keywords: [String(message.keyword || "").trim()], provider: "google_ads", target: {country_code: message.countryCode || "US", language_code: "en", location_target: {country_code: message.countryCode || "US"}}})}).then(data => sendResponse({ok: true, data})).catch(error => sendResponse({ok: false, error: error.message})); return true; }
  if (message?.type === "NS_LOOKUP_DR") { const urls = (Array.isArray(message.urls) ? message.urls : []).filter(u => { try { return ["http:", "https:"].includes(new URL(u).protocol); } catch { return false; } }).slice(0, 20); api("/overlay/metrics", {method: "POST", body: JSON.stringify({urls})}).then(data => sendResponse({ok: data.provider === "ahrefs", data})).catch(error => sendResponse({ok: false, error: error.message})); return true; }
  if (message?.type === "NS_GET_SETTINGS") { settings().then(data => sendResponse({ok: true, data})); return true; }
  if (message?.type === "NS_SAVE_SETTINGS") { chrome.storage.local.set({apiBase: String(message.apiBase || DEFAULT_API).trim(), accessToken: String(message.accessToken || "").trim()}, () => sendResponse({ok: true})); return true; }
});
