"""add immutable runs events and evidence lineage

Revision ID: 2aa370e8bd79
Revises: a97fe719ed01
Create Date: 2026-08-10 20:55:40.799430
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '2aa370e8bd79'
down_revision: Union[str, None] = 'a97fe719ed01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('min_population', sa.Integer(), nullable=False),
    sa.Column('max_population', sa.Integer(), nullable=False),
    sa.Column('min_search_volume', sa.Integer(), nullable=False),
    sa.Column('da_threshold', sa.Float(), nullable=False),
    sa.Column('required_low_da_count', sa.Integer(), nullable=False),
    sa.Column('organic_depth', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('language_code', sa.String(length=16), nullable=False),
    sa.Column('location_config', sa.JSON(), nullable=False),
    sa.Column('enabled_gates', sa.JSON(), nullable=False),
    sa.Column('provider_snapshot', sa.JSON(), nullable=False),
    sa.Column('freshness_policy_snapshot', sa.JSON(), nullable=False),
    sa.Column('configuration_snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_project_id'), 'runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_runs_status'), 'runs', ['status'], unique=False)
    op.create_table('project_candidates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('candidate_entity_id', sa.String(), nullable=False),
    sa.Column('original_input', sa.String(length=500), nullable=True),
    sa.Column('broad_category', sa.String(length=160), nullable=True),
    sa.Column('micro_niche', sa.String(length=160), nullable=True),
    sa.Column('nano_niche', sa.String(length=160), nullable=True),
    sa.Column('display_keyword', sa.String(length=400), nullable=False),
    sa.Column('current_status', sa.String(length=40), nullable=False),
    sa.Column('automatic_status', sa.String(length=40), nullable=True),
    sa.Column('manual_status', sa.String(length=40), nullable=True),
    sa.Column('manual_override_reason', sa.String(length=2000), nullable=True),
    sa.Column('current_reason_codes', sa.JSON(), nullable=False),
    sa.Column('latest_run_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_entity_id'], ['candidate_entities.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'candidate_entity_id', name='uq_project_candidate_entity')
    )
    op.create_index(op.f('ix_project_candidates_candidate_entity_id'), 'project_candidates', ['candidate_entity_id'], unique=False)
    op.create_index(op.f('ix_project_candidates_latest_run_id'), 'project_candidates', ['latest_run_id'], unique=False)
    op.create_index(op.f('ix_project_candidates_project_id'), 'project_candidates', ['project_id'], unique=False)
    op.create_table('run_candidates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('project_candidate_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('automatic_status', sa.String(length=40), nullable=True),
    sa.Column('reason_codes', sa.JSON(), nullable=False),
    sa.Column('population_evidence_id', sa.String(), nullable=True),
    sa.Column('search_volume_evidence_id', sa.String(), nullable=True),
    sa.Column('serp_snapshot_id', sa.String(), nullable=True),
    sa.Column('da_threshold_used', sa.Float(), nullable=True),
    sa.Column('required_low_da_count_used', sa.Integer(), nullable=True),
    sa.Column('organic_results_evaluated', sa.Integer(), nullable=True),
    sa.Column('authority_results_available', sa.Integer(), nullable=True),
    sa.Column('low_da_count', sa.Integer(), nullable=True),
    sa.Column('primary_gate_passed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['population_evidence_id'], ['population_evidence.id'], ),
    sa.ForeignKeyConstraint(['project_candidate_id'], ['project_candidates.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['search_volume_evidence_id'], ['search_volume_evidence.id'], ),
    sa.ForeignKeyConstraint(['serp_snapshot_id'], ['serp_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'project_candidate_id', name='uq_run_project_candidate')
    )
    op.create_index(op.f('ix_run_candidates_project_candidate_id'), 'run_candidates', ['project_candidate_id'], unique=False)
    op.create_index(op.f('ix_run_candidates_run_id'), 'run_candidates', ['run_id'], unique=False)
    op.create_table('candidate_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('run_candidate_id', sa.String(), nullable=True),
    sa.Column('project_candidate_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('previous_status', sa.String(length=40), nullable=True),
    sa.Column('resulting_status', sa.String(length=40), nullable=True),
    sa.Column('reason_code', sa.String(length=100), nullable=True),
    sa.Column('evidence_references', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_candidate_id'], ['project_candidates.id'], ),
    sa.ForeignKeyConstraint(['run_candidate_id'], ['run_candidates.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_events_created_at'), 'candidate_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_candidate_events_event_type'), 'candidate_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_candidate_events_project_candidate_id'), 'candidate_events', ['project_candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_events_run_candidate_id'), 'candidate_events', ['run_candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_events_run_id'), 'candidate_events', ['run_id'], unique=False)
    op.create_table('run_candidate_authority_evidence',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_candidate_id', sa.String(), nullable=False),
    sa.Column('serp_result_row_id', sa.String(), nullable=False),
    sa.Column('authority_evidence_id', sa.String(), nullable=False),
    sa.Column('ranking_position', sa.Integer(), nullable=True),
    sa.Column('da_value_used', sa.Float(), nullable=True),
    sa.Column('counted_as_low_da', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['authority_evidence_id'], ['authority_evidence.id'], ),
    sa.ForeignKeyConstraint(['run_candidate_id'], ['run_candidates.id'], ),
    sa.ForeignKeyConstraint(['serp_result_row_id'], ['serp_results.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_candidate_id', 'serp_result_row_id', name='uq_run_candidate_serp_authority')
    )
    op.create_index(op.f('ix_run_candidate_authority_evidence_authority_evidence_id'), 'run_candidate_authority_evidence', ['authority_evidence_id'], unique=False)
    op.create_index(op.f('ix_run_candidate_authority_evidence_run_candidate_id'), 'run_candidate_authority_evidence', ['run_candidate_id'], unique=False)
    op.create_index(op.f('ix_run_candidate_authority_evidence_serp_result_row_id'), 'run_candidate_authority_evidence', ['serp_result_row_id'], unique=False)
    with op.batch_alter_table('provider_calls') as batch_op:
        batch_op.add_column(sa.Column('run_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('run_candidate_id', sa.String(), nullable=True))
        batch_op.create_index(op.f('ix_provider_calls_run_candidate_id'), ['run_candidate_id'], unique=False)
        batch_op.create_index(op.f('ix_provider_calls_run_id'), ['run_id'], unique=False)
        batch_op.create_foreign_key('fk_provider_calls_run', 'runs', ['run_id'], ['id'])
        batch_op.create_foreign_key('fk_provider_calls_run_candidate', 'run_candidates', ['run_candidate_id'], ['id'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider_calls') as batch_op:
        batch_op.drop_constraint('fk_provider_calls_run_candidate', type_='foreignkey')
        batch_op.drop_constraint('fk_provider_calls_run', type_='foreignkey')
        batch_op.drop_index(op.f('ix_provider_calls_run_id'))
        batch_op.drop_index(op.f('ix_provider_calls_run_candidate_id'))
        batch_op.drop_column('run_candidate_id')
        batch_op.drop_column('run_id')
    op.drop_index(op.f('ix_run_candidate_authority_evidence_serp_result_row_id'), table_name='run_candidate_authority_evidence')
    op.drop_index(op.f('ix_run_candidate_authority_evidence_run_candidate_id'), table_name='run_candidate_authority_evidence')
    op.drop_index(op.f('ix_run_candidate_authority_evidence_authority_evidence_id'), table_name='run_candidate_authority_evidence')
    op.drop_table('run_candidate_authority_evidence')
    op.drop_index(op.f('ix_candidate_events_run_id'), table_name='candidate_events')
    op.drop_index(op.f('ix_candidate_events_run_candidate_id'), table_name='candidate_events')
    op.drop_index(op.f('ix_candidate_events_project_candidate_id'), table_name='candidate_events')
    op.drop_index(op.f('ix_candidate_events_event_type'), table_name='candidate_events')
    op.drop_index(op.f('ix_candidate_events_created_at'), table_name='candidate_events')
    op.drop_table('candidate_events')
    op.drop_index(op.f('ix_run_candidates_run_id'), table_name='run_candidates')
    op.drop_index(op.f('ix_run_candidates_project_candidate_id'), table_name='run_candidates')
    op.drop_table('run_candidates')
    op.drop_index(op.f('ix_project_candidates_project_id'), table_name='project_candidates')
    op.drop_index(op.f('ix_project_candidates_latest_run_id'), table_name='project_candidates')
    op.drop_index(op.f('ix_project_candidates_candidate_entity_id'), table_name='project_candidates')
    op.drop_table('project_candidates')
    op.drop_index(op.f('ix_runs_status'), table_name='runs')
    op.drop_index(op.f('ix_runs_project_id'), table_name='runs')
    op.drop_table('runs')
    # ### end Alembic commands ###
