"""add keyword difficulty evidence and configuration

Revision ID: 5c45b58975e9
Revises: 9d6445dbc7ae
Create Date: 2026-08-10 21:56:16.712161
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '5c45b58975e9'
down_revision: Union[str, None] = '9d6445dbc7ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyword_difficulty_evidence',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('candidate_entity_id', sa.String(), nullable=False),
    sa.Column('keyword', sa.String(length=400), nullable=False),
    sa.Column('location_name', sa.String(length=240), nullable=True),
    sa.Column('language_code', sa.String(length=16), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('metric_type', sa.String(length=40), nullable=False),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('source_kind', sa.String(length=40), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('request_metadata', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('fresh_until', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_entity_id'], ['candidate_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keyword_difficulty_evidence_candidate_entity_id'), 'keyword_difficulty_evidence', ['candidate_entity_id'], unique=False)
    op.create_index(op.f('ix_keyword_difficulty_evidence_keyword'), 'keyword_difficulty_evidence', ['keyword'], unique=False)
    op.create_index(op.f('ix_keyword_difficulty_evidence_provider'), 'keyword_difficulty_evidence', ['provider'], unique=False)
    with op.batch_alter_table('run_candidates') as batch_op:
        batch_op.add_column(sa.Column('keyword_difficulty_evidence_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('kd_value_used', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('kd_status', sa.String(length=30), nullable=True))
        batch_op.create_foreign_key('fk_run_candidates_kd_evidence', 'keyword_difficulty_evidence', ['keyword_difficulty_evidence_id'], ['id'])
    with op.batch_alter_table('runs') as batch_op:
        batch_op.add_column(sa.Column('kd_enabled', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('kd_provider', sa.String(length=80), nullable=False, server_default='moz'))
        batch_op.add_column(sa.Column('kd_threshold', sa.Float(), nullable=False, server_default='15'))
        batch_op.add_column(sa.Column('kd_operator', sa.String(length=4), nullable=False, server_default='<'))
        batch_op.add_column(sa.Column('kd_mode', sa.String(length=20), nullable=False, server_default='PRIORITY'))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs') as batch_op:
        batch_op.drop_column('kd_mode')
        batch_op.drop_column('kd_operator')
        batch_op.drop_column('kd_threshold')
        batch_op.drop_column('kd_provider')
        batch_op.drop_column('kd_enabled')
    with op.batch_alter_table('run_candidates') as batch_op:
        batch_op.drop_constraint('fk_run_candidates_kd_evidence', type_='foreignkey')
        batch_op.drop_column('kd_status')
        batch_op.drop_column('kd_value_used')
        batch_op.drop_column('keyword_difficulty_evidence_id')
    op.drop_index(op.f('ix_keyword_difficulty_evidence_provider'), table_name='keyword_difficulty_evidence')
    op.drop_index(op.f('ix_keyword_difficulty_evidence_keyword'), table_name='keyword_difficulty_evidence')
    op.drop_index(op.f('ix_keyword_difficulty_evidence_candidate_entity_id'), table_name='keyword_difficulty_evidence')
    op.drop_table('keyword_difficulty_evidence')
    # ### end Alembic commands ###
