"""add recalculation run metadata

Revision ID: 6f66991da474
Revises: ba2281e098cb
Create Date: 2026-08-10 21:36:34.979710
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '6f66991da474'
down_revision: Union[str, None] = 'ba2281e098cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs') as batch_op:
        batch_op.add_column(sa.Column('run_type', sa.String(length=30), nullable=False, server_default='STANDARD'))
        batch_op.add_column(sa.Column('parent_run_id', sa.String(), nullable=True))
        batch_op.create_index(op.f('ix_runs_parent_run_id'), ['parent_run_id'], unique=False)
        batch_op.create_index(op.f('ix_runs_run_type'), ['run_type'], unique=False)
        batch_op.create_foreign_key('fk_runs_parent_run', 'runs', ['parent_run_id'], ['id'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs') as batch_op:
        batch_op.drop_constraint('fk_runs_parent_run', type_='foreignkey')
        batch_op.drop_index(op.f('ix_runs_run_type'))
        batch_op.drop_index(op.f('ix_runs_parent_run_id'))
        batch_op.drop_column('parent_run_id')
        batch_op.drop_column('run_type')
    # ### end Alembic commands ###
