"""initial foundation schema

Revision ID: 903990425cdf
Revises: 
Create Date: 2026-08-10 20:40:50.609363
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '903990425cdf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authority_metrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('target_key', sa.String(length=2000), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('da', sa.Float(), nullable=True),
    sa.Column('pa', sa.Float(), nullable=True),
    sa.Column('spam_score', sa.Float(), nullable=True),
    sa.Column('linking_root_domains', sa.Integer(), nullable=True),
    sa.Column('backlinks', sa.Integer(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authority_metrics_provider'), 'authority_metrics', ['provider'], unique=False)
    op.create_index(op.f('ix_authority_metrics_target_key'), 'authority_metrics', ['target_key'], unique=False)
    op.create_table('cities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('state_code', sa.String(length=2), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('population_vintage', sa.String(length=40), nullable=False),
    sa.Column('census_geo_id', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'state_code', 'population_vintage', name='uq_city_vintage')
    )
    op.create_index(op.f('ix_cities_name'), 'cities', ['name'], unique=False)
    op.create_index(op.f('ix_cities_population'), 'cities', ['population'], unique=False)
    op.create_index(op.f('ix_cities_state_code'), 'cities', ['state_code'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('profile_snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_entities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('canonical_identity', sa.String(length=700), nullable=False),
    sa.Column('identity_key', sa.String(length=64), nullable=False),
    sa.Column('service_term_normalized', sa.String(length=240), nullable=False),
    sa.Column('city_id', sa.String(), nullable=False),
    sa.Column('language_code', sa.String(length=16), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('canonical_keyword', sa.String(length=400), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_entities_canonical_identity'), 'candidate_entities', ['canonical_identity'], unique=True)
    op.create_index(op.f('ix_candidate_entities_city_id'), 'candidate_entities', ['city_id'], unique=False)
    op.create_index(op.f('ix_candidate_entities_identity_key'), 'candidate_entities', ['identity_key'], unique=True)
    op.create_index(op.f('ix_candidate_entities_service_term_normalized'), 'candidate_entities', ['service_term_normalized'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('city_id', sa.String(), nullable=True),
    sa.Column('broad_category', sa.String(length=160), nullable=True),
    sa.Column('micro_niche', sa.String(length=160), nullable=True),
    sa.Column('service_term', sa.String(length=240), nullable=False),
    sa.Column('normalized_keyword', sa.String(length=400), nullable=False),
    sa.Column('display_keyword', sa.String(length=400), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('search_volume', sa.Integer(), nullable=True),
    sa.Column('cpc', sa.Float(), nullable=True),
    sa.Column('low_da_count', sa.Integer(), nullable=True),
    sa.Column('secondary_score', sa.Float(), nullable=True),
    sa.Column('automatic_pass', sa.Boolean(), nullable=True),
    sa.Column('reason_codes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'normalized_keyword', name='uq_project_keyword')
    )
    op.create_index(op.f('ix_candidates_city_id'), 'candidates', ['city_id'], unique=False)
    op.create_index(op.f('ix_candidates_normalized_keyword'), 'candidates', ['normalized_keyword'], unique=False)
    op.create_index(op.f('ix_candidates_project_id'), 'candidates', ['project_id'], unique=False)
    op.create_index(op.f('ix_candidates_service_term'), 'candidates', ['service_term'], unique=False)
    op.create_table('serp_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('candidate_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_serp_snapshots_candidate_id'), 'serp_snapshots', ['candidate_id'], unique=False)
    op.create_table('serp_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=True),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('root_domain', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['serp_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_serp_results_root_domain'), 'serp_results', ['root_domain'], unique=False)
    op.create_index(op.f('ix_serp_results_snapshot_id'), 'serp_results', ['snapshot_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_serp_results_snapshot_id'), table_name='serp_results')
    op.drop_index(op.f('ix_serp_results_root_domain'), table_name='serp_results')
    op.drop_table('serp_results')
    op.drop_index(op.f('ix_serp_snapshots_candidate_id'), table_name='serp_snapshots')
    op.drop_table('serp_snapshots')
    op.drop_index(op.f('ix_candidates_service_term'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_project_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_normalized_keyword'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_city_id'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_candidate_entities_service_term_normalized'), table_name='candidate_entities')
    op.drop_index(op.f('ix_candidate_entities_identity_key'), table_name='candidate_entities')
    op.drop_index(op.f('ix_candidate_entities_city_id'), table_name='candidate_entities')
    op.drop_index(op.f('ix_candidate_entities_canonical_identity'), table_name='candidate_entities')
    op.drop_table('candidate_entities')
    op.drop_table('projects')
    op.drop_index(op.f('ix_cities_state_code'), table_name='cities')
    op.drop_index(op.f('ix_cities_population'), table_name='cities')
    op.drop_index(op.f('ix_cities_name'), table_name='cities')
    op.drop_table('cities')
    op.drop_index(op.f('ix_authority_metrics_target_key'), table_name='authority_metrics')
    op.drop_index(op.f('ix_authority_metrics_provider'), table_name='authority_metrics')
    op.drop_table('authority_metrics')
    # ### end Alembic commands ###
