"""add freshness policy mode

Revision ID: 9d6445dbc7ae
Revises: 6f66991da474
Create Date: 2026-08-10 21:45:21.527160
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '9d6445dbc7ae'
down_revision: Union[str, None] = '6f66991da474'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('freshness_policy', sa.String(length=40), nullable=False))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'freshness_policy')
    # ### end Alembic commands ###
