"""add evidence cache provenance and provider calls

Revision ID: a97fe719ed01
Revises: 903990425cdf
Create Date: 2026-08-10 20:50:07.453904
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = 'a97fe719ed01'
down_revision: Union[str, None] = '903990425cdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_cache',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cache_key', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('operation', sa.String(length=100), nullable=False),
    sa.Column('evidence_type', sa.String(length=60), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('fresh_until', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.String(length=2000), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_cache_cache_key'), 'provider_cache', ['cache_key'], unique=True)
    op.create_index(op.f('ix_provider_cache_provider'), 'provider_cache', ['provider'], unique=False)
    op.create_table('provider_calls',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('stage', sa.String(length=60), nullable=False),
    sa.Column('operation', sa.String(length=100), nullable=False),
    sa.Column('request_cache_key', sa.String(length=128), nullable=False),
    sa.Column('outcome', sa.String(length=30), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('source_kind', sa.String(length=40), nullable=False),
    sa.Column('units', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('actual_cost', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('error_category', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_calls_provider'), 'provider_calls', ['provider'], unique=False)
    op.create_index(op.f('ix_provider_calls_request_cache_key'), 'provider_calls', ['request_cache_key'], unique=False)
    op.create_index(op.f('ix_provider_calls_stage'), 'provider_calls', ['stage'], unique=False)
    op.create_table('import_batches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('source_kind', sa.String(length=40), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=True),
    sa.Column('file_name', sa.String(length=500), nullable=True),
    sa.Column('file_hash', sa.String(length=128), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('accepted_count', sa.Integer(), nullable=False),
    sa.Column('rejected_count', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_batches_project_id'), 'import_batches', ['project_id'], unique=False)
    op.create_table('authority_evidence',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('candidate_entity_id', sa.String(), nullable=True),
    sa.Column('target_url', sa.String(length=2000), nullable=False),
    sa.Column('root_domain', sa.String(length=500), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('source_kind', sa.String(length=40), nullable=False),
    sa.Column('da', sa.Float(), nullable=True),
    sa.Column('pa', sa.Float(), nullable=True),
    sa.Column('spam_score', sa.Float(), nullable=True),
    sa.Column('linking_root_domains', sa.Integer(), nullable=True),
    sa.Column('backlinks', sa.Integer(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('request_metadata', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('fresh_until', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_entity_id'], ['candidate_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authority_evidence_candidate_entity_id'), 'authority_evidence', ['candidate_entity_id'], unique=False)
    op.create_index(op.f('ix_authority_evidence_provider'), 'authority_evidence', ['provider'], unique=False)
    op.create_index(op.f('ix_authority_evidence_root_domain'), 'authority_evidence', ['root_domain'], unique=False)
    op.create_index(op.f('ix_authority_evidence_target_url'), 'authority_evidence', ['target_url'], unique=False)
    op.create_table('population_evidence',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('candidate_entity_id', sa.String(), nullable=False),
    sa.Column('city_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('source_kind', sa.String(length=40), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('population_vintage', sa.String(length=40), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('source_metadata', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('fresh_until', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_entity_id'], ['candidate_entities.id'], ),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_population_evidence_candidate_entity_id'), 'population_evidence', ['candidate_entity_id'], unique=False)
    op.create_index(op.f('ix_population_evidence_city_id'), 'population_evidence', ['city_id'], unique=False)
    op.create_table('search_volume_evidence',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('candidate_entity_id', sa.String(), nullable=False),
    sa.Column('keyword', sa.String(length=400), nullable=False),
    sa.Column('location_name', sa.String(length=240), nullable=False),
    sa.Column('language_code', sa.String(length=16), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('source_kind', sa.String(length=40), nullable=False),
    sa.Column('avg_monthly_searches', sa.Integer(), nullable=True),
    sa.Column('cpc', sa.Float(), nullable=True),
    sa.Column('competition', sa.Float(), nullable=True),
    sa.Column('monthly_history', sa.JSON(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('request_metadata', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('fresh_until', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_entity_id'], ['candidate_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_volume_evidence_candidate_entity_id'), 'search_volume_evidence', ['candidate_entity_id'], unique=False)
    op.create_index(op.f('ix_search_volume_evidence_keyword'), 'search_volume_evidence', ['keyword'], unique=False)
    op.create_index(op.f('ix_search_volume_evidence_location_name'), 'search_volume_evidence', ['location_name'], unique=False)
    op.create_index(op.f('ix_search_volume_evidence_provider'), 'search_volume_evidence', ['provider'], unique=False)
    op.create_index('ix_sv_evidence_request', 'search_volume_evidence', ['keyword', 'location_name', 'language_code', 'country_code'], unique=False)
    with op.batch_alter_table('serp_results') as batch_op:
        batch_op.add_column(sa.Column('display_domain', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('result_type', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('raw_row', sa.JSON(), nullable=False, server_default=sa.text("'{}'")))
    with op.batch_alter_table('serp_snapshots') as batch_op:
        batch_op.add_column(sa.Column('candidate_entity_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('keyword', sa.String(length=400), nullable=True))
        batch_op.add_column(sa.Column('location_name', sa.String(length=240), nullable=True))
        batch_op.add_column(sa.Column('language_code', sa.String(length=16), nullable=False, server_default='en'))
        batch_op.add_column(sa.Column('country_code', sa.String(length=2), nullable=False, server_default='US'))
        batch_op.add_column(sa.Column('device_profile', sa.String(length=30), nullable=False, server_default='desktop'))
        batch_op.add_column(sa.Column('requested_depth', sa.Integer(), nullable=False, server_default='10'))
        batch_op.add_column(sa.Column('source_kind', sa.String(length=40), nullable=False, server_default='mock'))
        batch_op.add_column(sa.Column('fresh_until', sa.DateTime(), nullable=True))
        batch_op.create_index(op.f('ix_serp_snapshots_candidate_entity_id'), ['candidate_entity_id'], unique=False)
        batch_op.create_foreign_key('fk_serp_snapshots_candidate_entity', 'candidate_entities', ['candidate_entity_id'], ['id'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('serp_snapshots') as batch_op:
        batch_op.drop_constraint('fk_serp_snapshots_candidate_entity', type_='foreignkey')
        batch_op.drop_index(op.f('ix_serp_snapshots_candidate_entity_id'))
        batch_op.drop_column('fresh_until')
        batch_op.drop_column('source_kind')
        batch_op.drop_column('requested_depth')
        batch_op.drop_column('device_profile')
        batch_op.drop_column('country_code')
        batch_op.drop_column('language_code')
        batch_op.drop_column('location_name')
        batch_op.drop_column('keyword')
        batch_op.drop_column('candidate_entity_id')
    with op.batch_alter_table('serp_results') as batch_op:
        batch_op.drop_column('raw_row')
        batch_op.drop_column('result_type')
        batch_op.drop_column('display_domain')
    op.drop_index('ix_sv_evidence_request', table_name='search_volume_evidence')
    op.drop_index(op.f('ix_search_volume_evidence_provider'), table_name='search_volume_evidence')
    op.drop_index(op.f('ix_search_volume_evidence_location_name'), table_name='search_volume_evidence')
    op.drop_index(op.f('ix_search_volume_evidence_keyword'), table_name='search_volume_evidence')
    op.drop_index(op.f('ix_search_volume_evidence_candidate_entity_id'), table_name='search_volume_evidence')
    op.drop_table('search_volume_evidence')
    op.drop_index(op.f('ix_population_evidence_city_id'), table_name='population_evidence')
    op.drop_index(op.f('ix_population_evidence_candidate_entity_id'), table_name='population_evidence')
    op.drop_table('population_evidence')
    op.drop_index(op.f('ix_authority_evidence_target_url'), table_name='authority_evidence')
    op.drop_index(op.f('ix_authority_evidence_root_domain'), table_name='authority_evidence')
    op.drop_index(op.f('ix_authority_evidence_provider'), table_name='authority_evidence')
    op.drop_index(op.f('ix_authority_evidence_candidate_entity_id'), table_name='authority_evidence')
    op.drop_table('authority_evidence')
    op.drop_index(op.f('ix_import_batches_project_id'), table_name='import_batches')
    op.drop_table('import_batches')
    op.drop_index(op.f('ix_provider_calls_stage'), table_name='provider_calls')
    op.drop_index(op.f('ix_provider_calls_request_cache_key'), table_name='provider_calls')
    op.drop_index(op.f('ix_provider_calls_provider'), table_name='provider_calls')
    op.drop_table('provider_calls')
    op.drop_index(op.f('ix_provider_cache_provider'), table_name='provider_cache')
    op.drop_index(op.f('ix_provider_cache_cache_key'), table_name='provider_cache')
    op.drop_table('provider_cache')
    # ### end Alembic commands ###
