"""add run counters

Revision ID: ba2281e098cb
Revises: 2aa370e8bd79
Create Date: 2026-08-10 21:30:46.099181
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = 'ba2281e098cb'
down_revision: Union[str, None] = '2aa370e8bd79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('counters', sa.JSON(), nullable=False))
    op.add_column('runs', sa.Column('estimated_cost', sa.Float(), nullable=True))
    op.add_column('runs', sa.Column('actual_cost', sa.Float(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'actual_cost')
    op.drop_column('runs', 'estimated_cost')
    op.drop_column('runs', 'counters')
    # ### end Alembic commands ###
