from enum import StrEnum


class CandidateStatus(StrEnum):
    IMPORTED = "IMPORTED"
    POPULATION_PENDING = "POPULATION_PENDING"
    POPULATION_REJECTED = "POPULATION_REJECTED"
    SV_PENDING = "SV_PENDING"
    SV_REJECTED = "SV_REJECTED"
    SERP_PENDING = "SERP_PENDING"
    SERP_FETCHED = "SERP_FETCHED"
    AUTHORITY_PENDING = "AUTHORITY_PENDING"
    PRIMARY_REJECTED = "PRIMARY_REJECTED"
    SECONDARY_PENDING = "SECONDARY_PENDING"
    SECONDARY_COMPLETE = "SECONDARY_COMPLETE"
    MONETIZATION_PENDING = "MONETIZATION_PENDING"
    WATCHLIST = "WATCHLIST"
    PASS = "PASS"
    MANUALLY_REJECTED = "MANUALLY_REJECTED"
    MANUALLY_APPROVED = "MANUALLY_APPROVED"
    ERROR_RETRYABLE = "ERROR_RETRYABLE"
    ERROR_TERMINAL = "ERROR_TERMINAL"


class ReasonCode(StrEnum):
    POPULATION_BELOW_MIN = "POPULATION_BELOW_MIN"
    POPULATION_ABOVE_MAX = "POPULATION_ABOVE_MAX"
    SV_BELOW_THRESHOLD = "SV_BELOW_THRESHOLD"
    SV_MISSING = "SV_MISSING"
    SV_PROVIDER_CONFLICT = "SV_PROVIDER_CONFLICT"
    SERP_INSUFFICIENT_ORGANIC_RESULTS = "SERP_INSUFFICIENT_ORGANIC_RESULTS"
    LOW_DA_COUNT_BELOW_REQUIRED = "LOW_DA_COUNT_BELOW_REQUIRED"
    MONETIZATION_GEO_UNSUPPORTED = "MONETIZATION_GEO_UNSUPPORTED"
    MONETIZATION_INACTIVE = "MONETIZATION_INACTIVE"
    SEASONALITY_HARD_GATE = "SEASONALITY_HARD_GATE"
    MANUAL_REJECT = "MANUAL_REJECT"
    PROVIDER_ERROR = "PROVIDER_ERROR"
    DATA_INCOMPLETE = "DATA_INCOMPLETE"
    KD_ABOVE_THRESHOLD = "KD_ABOVE_THRESHOLD"
