"use client";
import { useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import { AppShell } from "../../components/AppShell";
import "./validator.css";
const API = process.env.NEXT_PUBLIC_API_BASE || "http://127.0.0.1:8000/api/v1";
const stages = ["Population", "Search Volume", "SERP", "DA Gate", "Deep Analysis", "KD", "Result"];
type Handoff = { handoff_id: string; evidence_id: string; keyword: string; search_volume: number | null; provider: string; country_code: string; status: string };
export default function Validator() { const params = useSearchParams(); const handoffId = params.get("handoff_id") || params.get("handoff"); const [handoffs, setHandoffs] = useState<Handoff[]>([]); const [selected, setSelected] = useState<Handoff | null>(null); const [project, setProject] = useState(""); const [id, setId] = useState(""); const [error, setError] = useState(""); const [preview, setPreview] = useState<any>(null); const [busy, setBusy] = useState(false);
  useEffect(() => { const token = sessionStorage.getItem("nicheforge_access_token"); fetch(`${API}${handoffId ? `/rank-rent/handoffs/${handoffId}` : "/rank-rent/handoffs"}`, { headers: token ? { Authorization: `Bearer ${token}` } : {} }).then(async response => { if (!response.ok) throw new Error("Handoff not found"); return response.json(); }).then(data => { const list = Array.isArray(data) ? data : [data]; setHandoffs(list); setSelected(list[0] || null); }).catch(() => { if (handoffId) setError("The requested Search Volume handoff could not be found."); }); }, [handoffId]);
  async function create() { const token = sessionStorage.getItem("nicheforge_access_token"); const response = await fetch(`${API}/projects`, { method: "POST", headers: { "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}) }, body: JSON.stringify({ name: project || "Rank & Rent Project" }) }); const data = await response.json(); if (!response.ok) throw Error(data.detail || "Project creation failed"); setId(data.id); }
  async function run() { if (!id) return setError("Create a project first."); setBusy(true); setError(""); try { const token = sessionStorage.getItem("nicheforge_access_token"); const response = await fetch(`${API}/projects/${id}/validation-preview`, { method: "POST", headers: { "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}) }, body: JSON.stringify({ profile: { min_population: 20000, max_population: 120000, min_search_volume: 260, da_threshold: 10, required_low_da_count: 4, ideal_weak_domains: 5, organic_depth: 10, kd_threshold: 30, kd_mode: "PRIORITY" } }) }); const data = await response.json(); if (!response.ok) throw Error(data.detail || "Preview failed"); setPreview(data); } catch (e) { setError(e instanceof Error ? e.message : "Preview failed"); } finally { setBusy(false); } }
  return <AppShell active="Niche Validator"><div className="page-head"><div><p className="eyebrow">Rank &amp; Rent</p><h1>Rank &amp; Rent Validator</h1><p className="muted">Preview stored evidence before starting a controlled validation run.</p></div></div><section className="card"><div className="stage-strip">{stages.map(stage => <span className="stage" key={stage}>{stage}</span>)}</div></section>{selected && <section className="card handoff-arrival"><h2>Imported from Search Volume</h2><p><strong>Keyword:</strong> {selected.keyword}</p><p><strong>Search Volume:</strong> {selected.search_volume ?? "Unavailable"}</p><p><strong>Provider:</strong> {selected.provider} · <strong>Evidence:</strong> reused</p><p><strong>Handoff status:</strong> {selected.status}</p><small>No provider calls have been made. Validation begins only after an explicit preview/start action.</small></section>}{handoffs.length > 1 && <section className="card"><h2>Search Volume Handoffs</h2><select value={selected?.handoff_id || ""} onChange={event => setSelected(handoffs.find(item => item.handoff_id === event.target.value) || null)}>{handoffs.map(item => <option value={item.handoff_id} key={item.handoff_id}>{item.keyword} · SV {item.search_volume ?? "—"}</option>)}</select></section>}<section className="card form-grid"><h2>Candidate Source</h2><label>Project name<input value={project} onChange={e => setProject(e.target.value)} /></label><button className="button primary" onClick={() => create().catch(e => setError(e.message))}>{id ? "Project saved" : "Create project"}</button><span className="muted">{id ? `Project ${id}` : "No project selected"}</span></section>{error && <div className="error-banner">{error}</div>}{id && <section className="card"><h2>Validation Preview</h2><p className="muted">Search Volume is evidence; downstream stages remain conditional. Preview makes zero provider calls.</p><button className="button secondary" onClick={run} disabled={busy}>{busy ? "Preparing preview…" : "Preview Validation"}</button>{preview && <div className="metric-grid"><Stat label="Candidates" value={preview.candidate_count} /><Stat label="Estimated work" value={preview.estimated_provider_calls} /><Stat label="Preview requests" value={preview.preview_network_requests} /></div>}<button className="button primary" disabled>Start Validation · UI-4C pending</button></section>}</AppShell>; }
function Stat({ label, value }: { label: string; value: unknown }) { return <div className="metric card"><span>{label}</span><strong>{String(value ?? "—")}</strong></div>; }
